#!/bin/bash
# Deploy script to deploy the website to GitHub Pages

echo "Updating project: $1..."
cd projects/$1
git checkout master
git pull
git branch -d gh-pages
git checkout --track origin/gh-pages

# Switching back to the project's main directory
cd ../..

echo "Committing the changes"
git add .
git commit -m "Update Project: $1"

echo "Deleting gh-pages branch..."
git branch -d gh-pages
git push origin --delete

echo "Re-create the gh-pages branch..."
git branch gh-pages

echo "Push gh-pages to origin/gh-pages"
git push origin gh-pages

echo "Deploy complete."
